apiVersion: v1
kind: Service
metadata:
  name: analytics-api
  namespace: roadguard
  labels:
    app: analytics-api
    app.kubernetes.io/name: analytics-api
    app.kubernetes.io/part-of: roadguard-system
spec:
  type: ClusterIP
  selector:
    app: analytics-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
