apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
  namespace: roadguard
spec:
  template:
    spec:
      serviceAccountName: web-portal-sa
      automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  namespace: roadguard
spec:
  template:
    spec:
      serviceAccountName: analytics-api-sa
      automountServiceAccountToken: false
