apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: roadguard

resources:
  - ../web-portal/deployment.yaml
  - ../web-portal/service.yaml
  - ../web-portal/hpa.yaml
  - ../analytics-api/deployment.yaml
  - ../analytics-api/service.yaml
  - ../analytics-api/hpa.yaml
  - serviceaccounts.yaml
  - routes.yaml

patchesStrategicMerge:
  - deployment-patches.yaml
