apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-portal-sa
  namespace: roadguard
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-api-sa
  namespace: roadguard
automountServiceAccountToken: false
